### ISSUE TITLE
"no color support" on Windows with windows-curses

### ISSUE THREAD

**Issue by thorstenkampe** [eikenb/terminal-colors#10]
colortest-python quits with an error on Windows with windows-curses. If I remove `if num_colors > 0:` in `_terminal`, the script works just fine.

I would suggest to take an EAFP approach than LBYL, meaning, not to test `curses.tigetnum('colors')`.

**Comment by pjfarleyiii** [comment]
But if one insists on LBYL then this change works too:

    if sys.platform == "win32":
        _stdscr = curses.initscr()
        curses.start_color()
        curses.use_default_colors()
        num_colors = min(256, curses.COLORS)
        curses.endwin()
    else:
        curses.setupterm()
        num_colors = curses.tigetnum('colors')

Tested on Win10, Python 3.8.9, windows-curses 2.2.0, in both cmd.exe console and WIndow Terminal.  Works just like it does on *ix systems.

HTH

Peter

**Comment by eikenb** [comment]
Hey @thorstenkampe, sorry for missing this for so long. Work related github email tends to drown out my personal repos and I missed this when it came in and just happened to visit the repo and find it. I'll address this soon. Thanks for reporting it and thanks @pjfarleyiii for the  alt-fix idea. I don't have ready access to a windows machine to test this on so will be fixing it blind.

**Comment by eikenb** [comment]
I think I'll just go with the EAFP version and just assume people interested in this software will use terminals that have some level of color support. That is I'm just going to remove the `if num_colors > 0:` and the check for None in main. I'll post a PR if you're curious.
