### ISSUE TITLE
shorten the basic colors chart

### ISSUE THREAD

**Issue by deluxghost** [eikenb/terminal-colors#2]
for the basic chart, there are 2 spaces on both sides of the text(gYw), but one space is clearly enough

these spaces just broke every line on my phone, and this may help testing on a small screen

**Comment by eikenb** [comment]
Sorry for completely ignoring this for so long. This software has 'just worked' for so long I didn't think to check and github doesn't really do a good job of informing you if any of your projects have open issues.

I'll look into this. Thanks for reporting it.
