### ISSUE TITLE
Publish to pip and/or npm

### ISSUE THREAD

**Issue by kutsan** [eikenb/terminal-colors#3]
Could you please upload this script to pip and/or npm? It makes things easier for everybody. Also, npm isn't only for JavaScript community, it's language-agnostic manager, that works too.

**Comment by eikenb** [comment]
Added the setup.py... if you see anything wrong with it let me know (it's been awhile since I wrote one). I'll upload it to pypi later.

**Comment by kutsan** [comment]
Thanks for that! We can install with this for now.

```sh
pip install git+https://github.com/eikenb/terminal-colors
```

**Comment by eikenb** [comment]
Just uploaded it to pypi. Got screwed by the can't upload same version twice thing (forgot about that)... so I switched to SEMVER based versioning and got a working version pushed.

Thanks for the idea.

**Comment by kutsan** [comment]
You rocks!
