### ISSUE TITLE
fix name

### ISSUE THREAD

**Issue by ghost** [eikenb/terminal-colors#4]
here:

https://github.com/eikenb/terminal-colors#help-output

it shows

~~~
Usage: colortest-python [options]
~~~

but the command is actually:

~~~
/usr/bin/terminal-colors
~~~

**Comment by eikenb** [comment]
Hey @cup, thanks for pointing that out. I must have grabbed that output after running it using the Debian package where it's named colortest-python (the packager requested it to have it go with the existing colortest package).

I'll be uploading a fixed version in a couple. Thanks again.
