### ISSUE TITLE
Migration to python3

### ISSUE THREAD

**Issue by elMor3no** [eikenb/terminal-colors#5]
Hi

My name is Pablo Mestre and I am interested in resuming the maintenance of your project to package in Debian where I leave it Jari Aalto 
https://salsa.debian.org/elMor3no-guest/colortest-python/commit/12e18a3f5db1e90c0d610423ed5db68f5690d80f

I noticed that although the terminal-color is compatible with python3 it has not yet fully migrated which will be a problem in the next real Debian.
https://salsa.debian.org/elMor3no-guest/colortest-python/commit/1a5fec2f6bbdec6cb7079548abd0ff0039eb80fd

I would like to know if you have plans to update the project to python3?

Best regards,

**Comment by eikenb** [comment]
@elMor3no... that's awesome! As a Debian user I liked having my little program in the distro. Thanks for picking it up!

What is needed? The code runs fine with python3. Do I need to change the `#!` line or something?

**Comment by elMor3no** [comment]
Hi... 

Yes, is needed change the #! on the python file... 
Now im use a patch to solve temporally but would be nice you update the project :)
https://salsa.debian.org/elMor3no-guest/colortest-python/commit/42dd557a2b9336777880ccc8aebee4f00eb9175c

**Comment by eikenb** [comment]
Just pushed up that fix. Released a new version (3.0.0) to commemorate the switch. :)
