### ISSUE TITLE
gpg signature to verified the code after its release

### ISSUE THREAD

**Issue by elMor3no** [eikenb/terminal-colors#7]
Hi 

Is possible you provide me the gpg signature for the project?
https://lintian.debian.org/tags/debian-watch-does-not-check-gpg-signature.html

Is a way of verifying that no third party has modified the code after its release

**Comment by ottok** [comment]
Here are easy to follow docs: https://wiki.debian.org/Creating%20signed%20GitHub%20releases

**Comment by eikenb** [comment]
Sorry for missing this, let me see what I can do.

**Comment by eikenb** [comment]
https://github.com/eikenb/terminal-colors/releases/tag/v3.0.1

Easy enough. Does that do it?

**Comment by elMor3no** [comment]
You need to add the GnuPG key

Step 6 on https://wiki.debian.org/Creating%20signed%20GitHub%20releases

gpg --armor --detach-sign mysoftware-0.4.tar.gz

**Comment by eikenb** [comment]
Sorry for the long delay. I'll try to get this done soon.

**Comment by eikenb** [comment]
Ok, done. I used my GPG key that is registered here on github. Let me know if this doesn't do it. Thanks for your patience.

**Comment by ottok** [comment]
I don't know what "my GPG key here on github" means. Can you state your key ID so we can store it downstream in  debian/upstream/signing-key.asc and use it to authenticate all future releases, thanks!

**Comment by ottok** [comment]
@eikenb What key did you use to sign?

**Comment by eikenb** [comment]
Sigh. Sorry for the continuing pain. Re-reading the instructions I see the GPG key is required to be uploaded to a public server. I've done this before in the past (long time ago) and it was never useful so I stopped worrying about it.
