### ISSUE TITLE
Correctly sign releases with GnuPG

### ISSUE THREAD

**Issue by ottok** [eikenb/terminal-colors#9]
In #7 signatures for releases were added.

However, the signature files are invalid. How did you create them? What key did you use?

Current signatures are not valid:
```
$ gpg --verify terminal-colors-3.0.1.zip.asc
gpg: no signed data
gpg: can't hash datafile: No data


$ gpg --verify terminal-colors-3.0.1.tar.gz.asc
gpg: no signed data
gpg: can't hash datafile: No data


$ cat terminal-colors-3.0.1.tar.gz.asc
-----BEGIN PGP SIGNATURE-----

iQEzBAABCgAdFiEEzPhKluB/h4GYxGUCPZqeWROpRaIFAl6KTvkACgkQPZqeWROp
RaL6/Af7BqGNEqXrlsH2p7gjpg3xFhu+bp8rULQQRtGYCukFM+q+uLBCEWWerIqQ
ocPB6cvIf4uSTTL8P8QIjykdjIcF7O4QTVcUiHDitpUDZW6ULoz4sUdJUHJP7T8T
Jyc+p4POXj0PZmpwldbVQHf6C/1KZpY/0ga7Uv5hkerQeTDobfatmn7ArRmzj2eC
DQabyz12ocsCMwE8rOBfj/GxWd5aOxXPA8E0+SujmLAJBNWuXTZy45txIZKsY+Eu
B9lXkdc/MdXC0r4a0DEK+OzvXOjTgXdp/UcPK0OxHtwdcMD0p/ywE93pWegtmL3o
VKbeDts1S/dA64ccSTCJiRxv/ThdXQ==
=wiqh
-----END PGP SIGNATURE-----

$ cat terminal-colors-3.0.1.zip.asc
-----BEGIN PGP SIGNATURE-----

iQEzBAABCgAdFiEEzPhKluB/h4GYxGUCPZqeWROpRaIFAl6KegIACgkQPZqeWROp
RaJRzAf9ELI7OxuUI3uxYw6mEa7t97a+HTsf5k0s9qrv8ZdeNtShyJxNuoEm2c0/
z1PTz6hSDdFjxGRsuD2OS2jRNuXQhVCvFR8rcRwnDXqhY+wcb4ve2MANFnfaAd4e
v9QIyFAcTDoTZd3qSwIIZk+3GJmEmwOwVQDj7vTYKgCrLFGLdarumQ/cVOLrQQEG
uIdt6C8KcTxerS/n6cfc8XBcFJrwOOmBkF7ikh/804uchh7qfehMg13BeDOycUHj
47uGXL9LLzNbWIqM76o3VaXuAQe+WlW2ckKTLFF3hZcJM6mrOtKWE/wLAlHBbmyE
S+QttPo2Y+4qnYzJx0Bn6rNcsuYKng==
=RmRF
-----END PGP SIGNATURE-----
```

**Comment by eikenb** [comment]
> However, the signature files are invalid. How did you create them? What key did you use?

I created them with the command `gpg --armor --detach-sign terminal-colors-3.0.1.tar.gz`

I used my personal key. It wasn't uploaded to the public servers before though as I don't normally use it that way, but it is now.

I'll re-create the .asc files and double check that they verify before uploading.

**Comment by eikenb** [comment]
I've re-created, verified, uploaded them, deleted the local copies, downloaded them and verified them again. Hopefully they are good this time.

I'll leave this open until you verify that you've been able to verify them.

**Comment by eikenb** [comment]
Oh... and I uploaded my keys to `pool.sks-keyservers.net`. Let me know if you need them uploaded to a different keyserver.

**Comment by elMor3no** [comment]
For some reason every time I try to download from Github I get the old one with errors... 

I download from https://pool.sks-keyservers.net/ the key you upload there and I get not error this time...

**Comment by elMor3no** [comment]
gpg --import signing-key.asc 
gpg: key 3D9A9E5913A945A2: public key "John Eikenberry (new rsa key) <jae@zhar.net>" imported
gpg: Total number processed: 1
gpg:               imported: 1

**Comment by ottok** [comment]
Thanks, works now!

```
$ gpg --verify colortest-python_3.0.1.orig.tar.gz.asc
gpg: assuming signed data in 'colortest-python_3.0.1.orig.tar.gz'
gpg: Signature made pe 10. huhtikuuta 2020 03.54.14 EEST
gpg:                using RSA key CCF84A96E07F878198C465023D9A9E5913A945A2
gpg: Good signature from "John Eikenberry (new rsa key) <jae@zhar.net>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: CCF8 4A96 E07F 8781 98C4  6502 3D9A 9E59 13A9 45A2
```
